fix: NoMethodError: undefined method `compact' for 899:Integer
/Users/oblomov/Documents/code/covid-storepoint/lib/models/cac_location.rb:169:in `arcgis_global_id'
/Users/oblomov/Documents/code/covid-storepoint/lib/models/cac_location.rb:83:in `add_arcgis_data_to_location'
/Users/oblomov/Documents/code/covid-storepoint/lib/models/cac_location.rb:65:in `block (2 levels) in all_from_api'
/Users/oblomov/Documents/code/covid-storepoint/lib/models/cac_location.rb:64:in `tap'
/Users/oblomov/Documents/code/covid-storepoint/lib/models/cac_location.rb:64:in `block in all_from_api'
/Users/oblomov/Documents/code/covid-storepoint/lib/models/cac_location.rb:63:in `map'
/Users/oblomov/Documents/code/covid-storepoint/lib/models/cac_location.rb:63:in `all_from_api'
/Users/oblomov/Documents/code/covid-storepoint/Rakefile:23:in `block (2 levels) in <top (required)>'
/Users/oblomov/Documents/code/covid-storepoint/Rakefile:7:in `timestamp'
/Users/oblomov/Documents/code/covid-storepoint/Rakefile:21:in `block in <top (required)>'
/Users/oblomov/.rbenv/versions/2.7.1/bin/bundle:23:in `load'
/Users/oblomov/.rbenv/versions/2.7.1/bin/bundle:23:in `<main>'
Tasks: TOP => export_cac_as_storepoint