fix: NameError: uninitialized constant CACLocation::ArcGISClient
NameError: uninitialized constant CACLocation::ArcGISClient
Did you mean?  ArcGISClientTest
    /Users/oblomov/Documents/code/covid-storepoint/lib/models/cac_location.rb:59:in `all_from_api'
    /Users/oblomov/Documents/code/covid-storepoint/Rakefile:38:in `block in <top (required)>'
    /Users/oblomov/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `block in execute'
    /Users/oblomov/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `each'
    /Users/oblomov/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `execute'
    /Users/oblomov/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
    /Users/oblomov/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `synchronize'
    /Users/oblomov/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
    /Users/oblomov/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:188:in `invoke'
    /Users/oblomov/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:160:in `invoke_task'
    /Users/oblomov/Documents/code/covid-storepoint/test/rake_test.rb:25:in `test_geocode_cac_locations'